Numpy LoadTXT

In [ ]:
import numpy as np

km = np.loadtxt("Data/carros-km.txt")
years = np.loadtxt("Data/carros-anos.txt", dtype=int)


km_media = km / (2018 - years)
print(km_media)

Array Simple Math

In [5]:
# Its possible to make a map count directly using simple math
anos = np.array([2003, 2020, 2013, 2005], dtype=int)

idade = 2023 - anos

print(idade[3])

18


Operations Between Arrays

In [9]:
sub_between_arrays = anos / idade
sub_between_arrays

array([100.15      , 673.33333333, 201.3       , 111.38888889])

Bidimensional Array

In [12]:
bidimensional = np.array([anos, idade])
print (bidimensional)
# dimension
bidimensional.shape 

[[2003 2020 2013 2005]
 [  20    3   10   18]]


(2, 4)

Slices in Array

In [5]:
import numpy as np
dados = np.array(
    [
        ['Roberto', 'casado', 'masculino'],
        ['Sheila', 'solteira', 'feminino'],
        ['Bruno', 'solteiro', 'masculino'],
        ['Rita', 'casada', 'feminino']
    ]
)
# Pegando apenas os homens
dados[0::2, :2]

array([['Roberto', 'casado'],
       ['Bruno', 'solteiro']], dtype='<U9')

Matrix Count

In [20]:
km = np.array([14444, 30000, 2000, 10000])
year = np.array([1990, 2003, 2020, 2006,])

info_cars = np.append(km, year).reshape(2,4)

info_cars = info_cars.copy()

info_cars.resize((3, 4), refcheck=False)
print('BEFORE')
print (info_cars)

info_cars[2] = info_cars[0] / (2023 - info_cars[1])
print ('AFTER')
print(info_cars)

BEFORE
[[14444 30000  2000 10000]
 [ 1990  2003  2020  2006]
 [    0     0     0     0]]
AFTER
[[14444 30000  2000 10000]
 [ 1990  2003  2020  2006]
 [  437  1500   666   588]]
